### ISSUE TITLE
tokio-compat-02 does not work for any library that uses tokio::time::delay_for

### ISSUE THREAD

**Issue by lovasoa** [LucioFranco/tokio-compat-02#1]
Hello !

reqwest is compatible with tokio 0.2, so I would have expected this crate to make it work with tokio 0.3. However, it looks like adding a timeout to requests makes reqwest require the runtime synchronously during `send`, not giving a chance to tokio_compat_02 to even receive the future. 

Is there a way to work around that ? Does this problem exist with other libraries ? Could this be documented in tokio-compat-02 ?
 
## Reproducible error

The following code panics at runtime : 

### `main.rs` 
```rust
use tokio_compat_02::FutureExt;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>>{
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(1)) // the code works without this line
        .build().unwrap();
    let body = client.get("http://postman-echo.com/get?x=y")
        .send().compat().await?
        .text().compat().await?;

    println!("body = {:?}", body);
    Ok(())
}
```

Removing the timeout makes the code work.

### `Cargo.toml` 
```toml
[package]
name = "hello_world"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3.0", features = ["full"] }
tokio-compat-02 = "0.1.0"
reqwest = "0.10.8"
```

### Backtrace

```
  17:     0x564a4305d1df - tokio::time::driver::handle::Handle::current::hf8848d51f6549010
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/time/driver/handle.rs:24
  18:     0x564a430bdf8f - tokio::time::driver::registration::Registration::new::h732389a1ee4f517d
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/time/driver/registration.rs:18
  19:     0x564a430bd865 - tokio::time::delay::delay_until::h113830ca763fcab4
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/time/delay.rs:19
  20:     0x564a430bd8e9 - tokio::time::delay::delay_for::hd299671a400d1562
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/time/delay.rs:56
  21:     0x564a42d2168c - core::ops::function::FnOnce::call_once::hfda903b17901e465
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  22:     0x564a42bf5661 - core::option::Option<T>::map::ha53e7fd9a36c6a7d
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:437
  23:     0x564a42c01075 - reqwest::async_impl::client::Client::execute_request::h088b54c49985a55b
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/async_impl/client.rs:1049
  24:     0x564a42ba194d - reqwest::async_impl::request::RequestBuilder::send::h487b0aca5a9d9e2a
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/async_impl/request.rs:410
  25:     0x564a42b4d644 - hello_world::main::{{closure}}::hbae9112fb1cfa227
                               at /tmp/hello_world/src/main.rs:9
```

<details>

```
thread 'main' panicked at 'there is no timer running, must be called from the context of Tokio runtime', /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/time/driver/handle.rs:25:14
stack backtrace:
   0:     0x564a431202d0 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x564a431202d0 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x564a431202d0 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x564a431202d0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x564a4313ff5c - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x564a4311ae57 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x564a431225b0 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x564a431225b0 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x564a431225b0 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x564a431222fc - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x564a43122c13 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x564a431227e9 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:     0x564a4312075c - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:     0x564a431227a9 - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:     0x564a4313e811 - core::panicking::panic_fmt::h4e2659771ebc78eb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
  15:     0x564a4313e5a3 - core::option::expect_failed::hd5a1da3a6b6bbb34
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
  16:     0x564a430b3141 - core::option::Option<T>::expect::h9d7d15f4679d0b8f
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:333
  17:     0x564a4305d1df - tokio::time::driver::handle::Handle::current::hf8848d51f6549010
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/time/driver/handle.rs:24
  18:     0x564a430bdf8f - tokio::time::driver::registration::Registration::new::h732389a1ee4f517d
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/time/driver/registration.rs:18
  19:     0x564a430bd865 - tokio::time::delay::delay_until::h113830ca763fcab4
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/time/delay.rs:19
  20:     0x564a430bd8e9 - tokio::time::delay::delay_for::hd299671a400d1562
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/time/delay.rs:56
  21:     0x564a42d2168c - core::ops::function::FnOnce::call_once::hfda903b17901e465
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  22:     0x564a42bf5661 - core::option::Option<T>::map::ha53e7fd9a36c6a7d
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:437
  23:     0x564a42c01075 - reqwest::async_impl::client::Client::execute_request::h088b54c49985a55b
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/async_impl/client.rs:1049
  24:     0x564a42ba194d - reqwest::async_impl::request::RequestBuilder::send::h487b0aca5a9d9e2a
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.8/src/async_impl/request.rs:410
  25:     0x564a42b4d644 - hello_world::main::{{closure}}::hbae9112fb1cfa227
                               at /tmp/hello_world/src/main.rs:9
  26:     0x564a42b53803 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h972b8e20ad86aad6
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:79
  27:     0x564a42b45f56 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h6a9c914bfaeb5dc7
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/park/thread.rs:263
  28:     0x564a42b4b108 - tokio::coop::with_budget::{{closure}}::hc97446a975be66bb
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/coop.rs:121
  29:     0x564a42b518b2 - std::thread::local::LocalKey<T>::try_with::h3016f5ea79a3c140
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:265
  30:     0x564a42b514d2 - std::thread::local::LocalKey<T>::with::he5206ae44ad18c49
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:241
  31:     0x564a42b45874 - tokio::coop::with_budget::haba85bd914ceb7e7
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/coop.rs:114
  32:     0x564a42b45874 - tokio::coop::budget::h4908e07ff8677677
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/coop.rs:98
  33:     0x564a42b45874 - tokio::park::thread::CachedParkThread::block_on::h5b6c83a18a451fac
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/park/thread.rs:263
  34:     0x564a42b4e51c - tokio::runtime::enter::Enter::block_on::h99bcb772d987584f
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/runtime/enter.rs:151
  35:     0x564a42b50e34 - tokio::runtime::thread_pool::ThreadPool::block_on::h3fe142ffd66093f5
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/runtime/thread_pool/mod.rs:80
  36:     0x564a42b4e0f2 - tokio::runtime::Runtime::block_on::h502481ad5895c8e6
                               at /home/ophir/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.3.0/src/runtime/mod.rs:422
  37:     0x564a42b4e355 - hello_world::main::hcdeaf6a10d54c5c7
                               at /tmp/hello_world/src/main.rs:4
  38:     0x564a42b523db - core::ops::function::FnOnce::call_once::hffc66f07dc4708d9
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  39:     0x564a42b50f2e - std::sys_common::backtrace::__rust_begin_short_backtrace::h4ff564984328cd04
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137
  40:     0x564a42b4e5d1 - std::rt::lang_start::{{closure}}::h0e55bbab106b5b7e
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66
  41:     0x564a431230e1 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6a3209f124be2235
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259
  42:     0x564a431230e1 - std::panicking::try::do_call::h88ce358792b64df0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373
  43:     0x564a431230e1 - std::panicking::try::h6311c259678e50fc
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337
  44:     0x564a431230e1 - std::panic::catch_unwind::h56c5716807d659a1
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379
  45:     0x564a431230e1 - std::rt::lang_start_internal::h73711f37ecfcb277
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51
  46:     0x564a42b4e5a7 - std::rt::lang_start::h4c47e7eb2de15c5f
                               at /home/ophir/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65
  47:     0x564a42b4e3fa - main
  48:     0x7f006f2800b3 - __libc_start_main
  49:     0x564a42b450be - _start
  50:                0x0 - <unknown>
```

</details>

**Comment by lovasoa** [comment]
The problem seems to come from the use of `tokio02::time::delay_for`. Here is a more simple reproduction : 

```rust
use tokio_compat_02::FutureExt;

fn main() {
    let duration = std::time::Duration::from_secs(1);
    tokio03::runtime::Builder::new_current_thread().build().unwrap().block_on(async move {
        tokio02::time::delay_for(duration).compat().await;
    });
}
```

```toml
[package]
name = "hello_world"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio03 = { package = "tokio", version = "0.3.0", features = ["full"] }
tokio02 = { package = "tokio", version = "0.2.22", features = ["full"] }
tokio-compat-02 = "0.1.0"
```

**Comment by Darksonn** [comment]
It panics before it even entered the compat region.
```rust
use tokio_compat_02::FutureExt;

fn main() {
    let duration = std::time::Duration::from_secs(1);
    tokio03::runtime::Builder::new_current_thread().build().unwrap().block_on(async move {
        let future = tokio02::time::delay_for(duration); // <-- this is what panics
        future.compat().await;
    });
}
```
Do this instead:
```rust
use tokio_compat_02::FutureExt;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    real_main().compat().await
}
async fn real_main() -> Result<(), Box<dyn std::error::Error>>{
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(1)) // the code works without this line
        .build().unwrap();

    let body = client.get("http://postman-echo.com/get?x=y")
        .send().await?
        .text().await?;

    println!("body = {:?}", body);
    Ok(())
}
```
The documentation on this will be improved soon.

**Comment by lovasoa** [comment]
`real_main().compat().await` prevents the user from using tokio 0.3 anywhere in his code. There is no point in doing that instead of just sticking to tokio 0.2, is there ?

**Comment by Darksonn** [comment]
Tokio 0.3 should still work inside the `.compat()` region.

**Comment by LucioFranco** [comment]
Yeah, I think the timer eagerly binds. Seems like this is resolved Thanks @Darksonn

**Comment by lovasoa** [comment]
Is this really resolved ? The user has no way to know whether a given method in a library will call `delay_for`, and thus cannot know where to apply `.compat()`

They can just run their entire program in tokio 0.2, but this is not really a solution.

**Comment by LucioFranco** [comment]
This is tricky for sure, but there is really no real solution here. If you have a lot of code that uses `tokio::spawn` and puts a timer in there, there is no way we can override that.

The solution here is to wrap your root application future in a compat call which will embed the ability to use tokio 0.2 items on anyruntime as long as you stay within that task (don't spawn out via tokio 0.3 `tokio::spawn`). I am not sure, what library you are using that has the issues with delay_for but the panic should bring up the location (hopefully).

**Comment by lovasoa** [comment]
Yes, the panic messages help. But the panic may never happen during development, and happen for the first time in production, depending on how your dependencies use `delay_for`. I think a good solution would be to warn about this problem in the README and in the documentation, and to advise users to not use this library in production.

**Comment by Darksonn** [comment]
You can add a `compat()` that covers the entire main function, along with one on any task spawned using Tokio 0.3's `tokio::spawn` function. You can't really do any better than that.

**Comment by Darksonn** [comment]
We could make a wrapper around Tokio 0.3's runtime that wraps any new task in the 0.2 context I guess. This would require adding a method to 0.2, but it's probably ok. This would be equivalent to adding a `.compat()` on every spawn.

**Comment by LucioFranco** [comment]
Personally, if you're not trigging this issue in tests then that code shouldn't be going to production. We have designed things to be discoverable as soon as you hit the code path. Its very deterministic in this sense. 

I think this library is fine to use in production, but if the concern is there you can also stick with 0.2 and wait to upgrade to 1.0. Mainly, this library was designed to be a quick short cut to allow you to get older libraries to work.

I don't think its worth it to invest into a runtime type and to provide that since we still can't hijack the static `tokio::spawn` calls either.
